FROM jenkins:latest
 
MAINTAINER lukas.elsner@sbb.ch

USER root

#RUN apt-get update && apt-get install -y s3cmd git-svn openldap-clients openssl xmlstarlet p7zip p7zip-plugins which ant ant-contrib && rm -rf /var/lib/apt/lists/*