mongo:
  image: mongo
  volumes:
    - data_mongo_chat_t_db:/data/db
    - data_mongo_chat_t_dump:/dump
  command: mongod --smallfiles --oplogSize 128
  restart: always

rocketchat:
  image: rocketchat/rocket.chat:latest
  volumes:
    - data_chat_t_uploads:/app/uploads
  environment:
    - PORT=8080
    - ROOT_URL=http://chat-t.sbb.ch
    - MONGO_URL=mongodb://mongo:27017/rocketchat
    - MAIL_URL=smtp://smtp-app.sbb.ch
    - HTTP_PROXY=http://webproxy.sbb.ch:8080
    - HTTPS_PROXY=http://webproxy.sbb.ch:8080
    - ADMIN_EMAIL=mwe@sbb.ch
    - ADMIN_PASS=wzuadminsbb
  links:
    - mongo:mongo
  ports:
    - 127.0.0.1:8251:8080
  restart: always
