#!/bin/bash
# jenkins        This shell script takes care of starting and stopping
#               the jenkins container.
#
# chkconfig: - 85 15

portoffset=50

opts="-p 80${portoffset}:80${portoffset} -p 90${portoffset}:90${portoffset} -p 9051:9051 -v /var/data/jenkins:/var/data/jenkins -d"
containername=jenkins-master
imagename=schweizerischebundesbahnen/jenkins-master

function start_container() {
	docker start $containername
}

function init_container() {
	docker run $opts --name $containername $imagename 
}

function stop_container() {
	docker stop $containername 
}

function reinitialize_container() {
        docker rm $containername
        init_container
}

case "$1" in
  start)
    start_container
    ;;
  stop)
    stop_container
    ;;
  init)
    init_container
    ;;
  reinitialize)
    reinitialize_container
    ;; 
  status)
    docker ps --all
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|init|reinitialize}"
    exit 2
esac
