FROM schweizerischebundesbahnen/jenkins-slave-jee
MAINTAINER Christoph Glanzmann <christoph.glanzmann@sbb.ch>

ENV labels "jee-release"

COPY jre16-java.security /opt/was70/java/jre/lib/security/java.security
COPY jre17-java.security /opt/was85/java_1.7_64/jre/lib/security/java.security
