ansible-tower:
  image: registry.sbb.ch/kd_wzu/ansible-tower:latest
  volumes:
    - /var/data/deploy:/external
  environment:
    SERVER_NAME: deploy-t.sbb.ch
    http_proxy: http://fsvctip:sommer11@webproxy.sbb.ch:8080
    https_proxy: http://fsvctip:sommer11@webproxy.sbb.ch:8080
  ports:
    - 8080:8080
    - 443:443
  restart: always