#@FIXME muss auf datacontainers zeigen
FROM registry.sbb.ch/kd_wzu/base
MAINTAINER Pascal Bieri <pascal.bieri@sbb.ch>
VOLUME /var/lib/mysql
#CMD ["tail", "-f","/dev/null"]
CMD ["echo", "Data container for Mysql DBs"]
